language: php

php:
- 5.5
- 5.6
- 7.0
- 7.1
env:
- TYPO3_VERSION=^7.6
- TYPO3_VERSION=^8.7
matrix:
  fast_finish: true
  exclude:
  - php: 5.5
    env: TYPO3_VERSION=^8.7
  - php: 5.6
    env: TYPO3_VERSION=^8.7

sudo: false

install:
- travis_retry composer install --no-interaction --prefer-source
- travis_retry composer require typo3/cms="$TYPO3_VERSION"

script:
  - .Build/bin/phpcs -n --standard=PSR2 --extensions=php --ignore=Tests/Unit/Seeder/SeedTest.php ./Classes/ ./Tests/
  - TYPO3_PATH_WEB=".Build/Web" .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
